// Generated by scripts/extract-html-layout.mjs from templates/contract.html
// 65 fields; regenerated 2026-06-28T15:11:28.216Z
// Source of truth: templates/contract.html + templates/contract.css
// Do not edit by hand - re-run the script after touching the HTML/CSS template.

import type { Field } from "./types";

export const FIELDS: Field[] = [
  { name: "ADRESA AGENTIE", kind: "text", x: 18.038, y: 13.933, w: 92, h: 3.2, fontSize: 8.8, font: "regular", align: "left", valign: "bottom", lineHeight: 1 },
  { name: "PROGRAM LUNI VINERI", kind: "text", x: 168.307, y: 15.433, w: 19.477, h: 3.2, fontSize: 8.3, font: "bold", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "PROGRAM WEEKEND", kind: "text", x: 168.307, y: 21.482, w: 19.477, h: 3.2, fontSize: 8.3, font: "bold", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "TELEFON AGENTIE", kind: "text", x: 168.307, y: 27.53, w: 19.477, h: 3.2, fontSize: 8.3, font: "bold", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NR CONTRACT", kind: "text", x: 26.546, y: 54.969, w: 35.001, h: 6.499, fontSize: 12, font: "bold", align: "center", valign: "middle", lineHeight: 1 },
  { name: "DIN", kind: "text", x: 74.252, y: 54.969, w: 50, h: 6.499, fontSize: 12, font: "bold", align: "center", valign: "middle", lineHeight: 1 },
  { name: "NUME", kind: "text", x: 39.788, y: 82.198, w: 80.002, h: 4.498, fontSize: 10.5, font: "bold", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "CNP_1", kind: "text", x: 18.038, y: 89.499, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_2", kind: "text", x: 24.992, y: 89.499, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_3", kind: "text", x: 31.946, y: 89.499, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_4", kind: "text", x: 38.899, y: 89.499, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_5", kind: "text", x: 45.853, y: 89.499, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_6", kind: "text", x: 52.807, y: 89.499, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_7", kind: "text", x: 59.761, y: 89.499, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_8", kind: "text", x: 66.715, y: 89.499, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_9", kind: "text", x: 73.669, y: 89.499, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_10", kind: "text", x: 80.623, y: 89.499, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_11", kind: "text", x: 87.576, y: 89.499, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_12", kind: "text", x: 94.53, y: 89.499, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_13", kind: "text", x: 101.484, y: 89.499, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "JUDET", kind: "text", x: 50.571, y: 96.192, w: 35.001, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "LOCALITATEA", kind: "text", x: 94.427, y: 96.192, w: 45.002, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "STRADA", kind: "text", x: 24.008, y: 102.497, w: 29.998, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NUMARUL STRAZII", kind: "text", x: 61.212, y: 102.497, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "BLOC", kind: "text", x: 78.212, y: 102.497, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "SCARA", kind: "text", x: 96.031, y: 102.497, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "APARTAMENT", kind: "text", x: 114.267, y: 102.497, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "LEGITIMAT CU", kind: "text", x: 146.089, y: 102.497, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "SERIE CI", kind: "text", x: 167.203, y: 102.497, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NR CI", kind: "text", x: 18.038, y: 108.103, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "ELIBERAT DE", kind: "text", x: 48.425, y: 108.103, w: 54.998, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE IMPRUMUT", kind: "text", x: 85.369, y: 114.408, w: 29.998, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE IMPRUMUT1", kind: "text", x: 19.799, y: 140.127, w: 28.688, h: 4.498, fontSize: 11, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "NR ZILE", kind: "text", x: 51.745, y: 140.127, w: 10.741, h: 4.498, fontSize: 11, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "DATA SCADENTA", kind: "text", x: 65.743, y: 140.127, w: 28.688, h: 4.498, fontSize: 11, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "COMISION PROCENT ZI", kind: "text", x: 97.689, y: 140.127, w: 28.688, h: 4.498, fontSize: 11, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "COMISION", kind: "text", x: 129.635, y: 140.127, w: 28.688, h: 4.498, fontSize: 11, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "SUMA DE RESTITUIT", kind: "text", x: 161.58, y: 140.127, w: 28.704, h: 4.498, fontSize: 11, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "GARANTII", kind: "text", x: 18.302, y: 154.697, w: 173.479, h: 19.468, fontSize: 9, font: "regular", align: "left", valign: "bottom", lineHeight: 1, multiline: true },
  { name: "DISPOZITIE DE PLATA NUMARUL", kind: "text", x: 47.759, y: 178.121, w: 9.997, h: 4.498, fontSize: 10, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "DIN1", kind: "text", x: 66.041, y: 178.121, w: 9.997, h: 4.498, fontSize: 10, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NUME1", kind: "text", x: 110.005, y: 178.121, w: 45.002, h: 4.498, fontSize: 10, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "LEGITIMAT CU1", kind: "text", x: 18.038, y: 184.459, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "SERIE CI1", kind: "text", x: 77.46, y: 184.459, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NR CI1", kind: "text", x: 94.663, y: 184.459, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE IMPRUMUT2", kind: "text", x: 128.34, y: 184.459, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE IMPRUMUT IN SCRIS", kind: "text", x: 18.038, y: 190.065, w: 60.001, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NR CONTRACT1", kind: "text", x: 160.824, y: 190.065, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "DIN2", kind: "text", x: 177.824, y: 190.065, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "SUMA PRIMITĂ LEI", kind: "text", x: 175.843, y: 197.949, w: 9.997, h: 4.498, fontSize: 10, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "CASIER_PLATA", kind: "text", x: 49.446, y: 205.143, w: 50, h: 6.999, fontSize: 10, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CLIENT_PLATA", kind: "text", x: 142.046, y: 205.143, w: 50, h: 6.999, fontSize: 10, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "DISPOZITIE INCASARE", kind: "text", x: 53.841, y: 214.838, w: 9.997, h: 4.498, fontSize: 10, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "DISPOZITIE INCASARE DIN", kind: "text", x: 74.082, y: 214.838, w: 9.997, h: 4.498, fontSize: 10, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "BENEFICIAR INCASARE", kind: "text", x: 85.575, y: 214.838, w: 54.998, h: 4.498, fontSize: 10, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "BENEFICIAR INCASARE CNP", kind: "text", x: 26.823, y: 221.176, w: 45.002, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "BENEFICIAR INCASARE SERIA CI", kind: "text", x: 122.28, y: 221.176, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "BENEFICIAR INCASARE NR CI", kind: "text", x: 139.482, y: 221.176, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "INCASARE NR CONTRACT", kind: "text", x: 43.158, y: 226.782, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "INCASARE DIN", kind: "text", x: 60.158, y: 226.782, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE INCASARE", kind: "text", x: 52.836, y: 233.087, w: 9.997, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE INCASARE IN SCRIS", kind: "text", x: 80.751, y: 233.087, w: 60.001, h: 4.498, fontSize: 10.5, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "CASIER_INCASARE", kind: "text", x: 49.446, y: 241.388, w: 50, h: 6.999, fontSize: 10, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CLIENT_INCASARE", kind: "text", x: 142.046, y: 241.388, w: 50, h: 6.999, fontSize: 10, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "DEBITOR_SIG", kind: "text", x: 38.825, y: 251.083, w: 50, h: 6.999, fontSize: 10, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
];

export const FIELDS_BY_NAME: Map<string, Field> = new Map(FIELDS.map((f) => [f.name, f]));

export function byName(name: string): Field | undefined {
  return FIELDS_BY_NAME.get(name);
}

export function cnpCells(): Field[] {
  const out: Field[] = [];
  for (let i = 1; i <= 13; i++) {
    const f = FIELDS_BY_NAME.get(`CNP_${i}`);
    if (f) out.push(f);
  }
  return out;
}

// Stamp overlay — kept out of FIELDS so the HTML extractor doesn't overwrite it.
// Anchor matches the position the legacy base PDF used (x≈167–198mm, y≈137–180mm).
export const STAMP_FIELD: Field = {
  name: "STAMP",
  kind: "image",
  imageName: "stamp-dogar",
  x: 172,
  y: 145,
  w: 31,
  h: 31,
  fontSize: 0,
  font: "regular",
  align: "left",
  valign: "top",
};
