// Generated by scripts/extract-html-layout.mjs from templates/contract.html
// 65 fields; regenerated 2026-06-29T18:21:12.717Z
// Source of truth: templates/contract.html + templates/contract.css
// Do not edit by hand - re-run the script after touching the HTML/CSS template.

import type { Field } from "./types";

export const FIELDS: Field[] = [
  { name: "ADRESA AGENTIE", kind: "text", x: 9.038, y: 11.258, w: 126.005, h: 2.7, fontSize: 11, font: "regular", align: "left", valign: "bottom", lineHeight: 1 },
  { name: "PROGRAM LUNI VINERI", kind: "text", x: 169.704, y: 10.972, w: 28.68, h: 3.097, fontSize: 10, font: "bold", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "PROGRAM WEEKEND", kind: "text", x: 169.704, y: 15.078, w: 28.68, h: 3.097, fontSize: 10, font: "bold", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "TELEFON AGENTIE", kind: "text", x: 169.704, y: 19.183, w: 28.68, h: 3.097, fontSize: 10, font: "bold", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NR CONTRACT", kind: "text", x: 16.698, y: 33.918, w: 35.001, h: 6.4, fontSize: 16, font: "bold", align: "center", valign: "middle", lineHeight: 1 },
  { name: "DIN", kind: "text", x: 61.419, y: 33.918, w: 50, h: 6.4, fontSize: 16, font: "bold", align: "center", valign: "middle", lineHeight: 1 },
  { name: "NUME", kind: "text", x: 35.241, y: 56.702, w: 58, h: 4.548, fontSize: 13.2, font: "bold", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "CNP_1", kind: "text", x: 104.023, y: 56.578, w: 6.846, h: 4.8, fontSize: 12, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_2", kind: "text", x: 111.117, y: 56.578, w: 6.846, h: 4.8, fontSize: 12, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_3", kind: "text", x: 118.212, y: 56.578, w: 6.851, h: 4.8, fontSize: 12, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_4", kind: "text", x: 125.31, y: 56.578, w: 6.846, h: 4.8, fontSize: 12, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_5", kind: "text", x: 132.404, y: 56.578, w: 6.846, h: 4.8, fontSize: 12, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_6", kind: "text", x: 139.499, y: 56.578, w: 6.851, h: 4.8, fontSize: 12, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_7", kind: "text", x: 146.597, y: 56.578, w: 6.846, h: 4.8, fontSize: 12, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_8", kind: "text", x: 153.692, y: 56.578, w: 6.851, h: 4.8, fontSize: 12, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_9", kind: "text", x: 160.79, y: 56.578, w: 6.846, h: 4.8, fontSize: 12, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_10", kind: "text", x: 167.885, y: 56.578, w: 6.846, h: 4.8, fontSize: 12, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_11", kind: "text", x: 174.979, y: 56.578, w: 6.851, h: 4.8, fontSize: 12, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_12", kind: "text", x: 182.078, y: 56.578, w: 6.846, h: 4.8, fontSize: 12, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_13", kind: "text", x: 189.172, y: 56.578, w: 6.851, h: 4.8, fontSize: 12, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "JUDET", kind: "text", x: 49.31, y: 61.923, w: 35.001, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "LOCALITATEA", kind: "text", x: 95.27, y: 61.923, w: 45.002, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "STRADA", kind: "text", x: 16.43, y: 67.405, w: 29.998, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NUMARUL STRAZII", kind: "text", x: 55.35, y: 67.405, w: 9.997, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "BLOC", kind: "text", x: 74.012, y: 67.405, w: 9.997, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "SCARA", kind: "text", x: 93.691, y: 67.405, w: 9.997, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "APARTAMENT", kind: "text", x: 113.887, y: 67.405, w: 9.997, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "LEGITIMAT CU", kind: "text", x: 150.897, y: 67.405, w: 13.999, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "SERIE CI", kind: "text", x: 178.659, y: 67.405, w: 13.999, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NR CI", kind: "text", x: 9.038, y: 72.739, w: 21.999, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "ELIBERAT DE", kind: "text", x: 56.272, y: 72.739, w: 54.998, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE IMPRUMUT", kind: "text", x: 92.385, y: 78.221, w: 29.998, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE IMPRUMUT1", kind: "text", x: 10.001, y: 99.595, w: 33.885, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "NR ZILE", kind: "text", x: 45.547, y: 99.595, w: 12.337, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "DATA SCADENTA", kind: "text", x: 59.546, y: 99.595, w: 33.885, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "COMISION PROCENT ZI", kind: "text", x: 95.093, y: 99.595, w: 33.885, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "COMISION", kind: "text", x: 130.639, y: 99.595, w: 33.885, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "SUMA DE RESTITUIT", kind: "text", x: 166.186, y: 99.595, w: 33.897, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "GARANTII", kind: "text", x: 9.302, y: 117.926, w: 191.479, h: 30.47, fontSize: 15, font: "regular", align: "left", valign: "bottom", lineHeight: 1, multiline: true },
  { name: "DISPOZITIE DE PLATA NUMARUL", kind: "text", x: 46.283, y: 151.005, w: 18.001, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "DIN1", kind: "text", x: 72.263, y: 151.005, w: 24, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NUME1", kind: "text", x: 137.626, y: 151.005, w: 45.002, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "LEGITIMAT CU1", kind: "text", x: 9.038, y: 156.487, w: 13.999, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "SERIE CI1", kind: "text", x: 84.215, y: 156.487, w: 13.999, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NR CI1", kind: "text", x: 107.136, y: 156.487, w: 21.999, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE IMPRUMUT2", kind: "text", x: 158.446, y: 156.487, w: 18.001, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE IMPRUMUT IN SCRIS", kind: "text", x: 9.038, y: 161.82, w: 60.001, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NR CONTRACT1", kind: "text", x: 171.511, y: 161.82, w: 16, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "DIN2", kind: "text", x: 9.038, y: 167.153, w: 24, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "SUMA PRIMITĂ LEI", kind: "text", x: 176.373, y: 173.235, w: 18.001, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "CASIER_PLATA", kind: "text", x: 45.936, y: 179.13, w: 58, h: 9.997, fontSize: 13, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CLIENT_PLATA", kind: "text", x: 143.046, y: 179.13, w: 58, h: 9.997, fontSize: 13, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "DISPOZITIE INCASARE", kind: "text", x: 54.188, y: 190.475, w: 18.001, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "DISPOZITIE INCASARE DIN", kind: "text", x: 82.715, y: 190.475, w: 24, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "BENEFICIAR INCASARE", kind: "text", x: 107.264, y: 190.475, w: 54.998, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "BENEFICIAR INCASARE CNP", kind: "text", x: 19.911, y: 195.957, w: 45.002, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "BENEFICIAR INCASARE SERIA CI", kind: "text", x: 127.365, y: 195.957, w: 13.999, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "BENEFICIAR INCASARE NR CI", kind: "text", x: 150.285, y: 195.957, w: 21.999, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "INCASARE NR CONTRACT", kind: "text", x: 89.077, y: 201.29, w: 16, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "INCASARE DIN", kind: "text", x: 113.746, y: 201.29, w: 24, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE INCASARE", kind: "text", x: 52.113, y: 206.772, w: 18.001, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE INCASARE IN SCRIS", kind: "text", x: 92.294, y: 206.772, w: 60.001, h: 4.548, fontSize: 13, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "CASIER_INCASARE", kind: "text", x: 45.936, y: 213.453, w: 58, h: 9.997, fontSize: 13, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CLIENT_INCASARE", kind: "text", x: 143.046, y: 213.453, w: 58, h: 9.997, fontSize: 13, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "DEBITOR_SIG", kind: "text", x: 31.185, y: 224.797, w: 70.002, h: 9.997, fontSize: 13, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
];

export const FIELDS_BY_NAME: Map<string, Field> = new Map(FIELDS.map((f) => [f.name, f]));

export function byName(name: string): Field | undefined {
  return FIELDS_BY_NAME.get(name);
}

export function cnpCells(): Field[] {
  const out: Field[] = [];
  for (let i = 1; i <= 13; i++) {
    const f = FIELDS_BY_NAME.get(`CNP_${i}`);
    if (f) out.push(f);
  }
  return out;
}

// Stamp overlay — kept out of FIELDS so the HTML extractor doesn't overwrite it.
// Anchor matches the position the legacy base PDF used (x≈167–198mm, y≈137–180mm).
export const STAMP_FIELD: Field = {
  name: "STAMP",
  kind: "image",
  imageName: "stamp-dogar",
  x: 172,
  y: 127,
  w: 31,
  h: 31,
  fontSize: 0,
  font: "regular",
  align: "left",
  valign: "top",
};
