// Generated by scripts/extract-html-layout.mjs from templates/contract.html
// 68 fields; regenerated 2026-06-25T20:47:29.020Z
// Source of truth: templates/contract.html + templates/contract.css
// Do not edit by hand - re-run the script after touching the HTML/CSS template.

import type { Field } from "./types";

export const FIELDS: Field[] = [
  { name: "ADRESA AGENTIE", kind: "text", x: 22.036, y: 14.933, w: 92, h: 3.2, fontSize: 8.8, font: "regular", align: "left", valign: "bottom", lineHeight: 1 },
  { name: "PROGRAM LUNI VINERI", kind: "text", x: 164.309, y: 16.434, w: 19.477, h: 3.2, fontSize: 8.3, font: "bold", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "PROGRAM WEEKEND", kind: "text", x: 164.309, y: 22.457, w: 19.477, h: 3.2, fontSize: 8.3, font: "bold", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "TELEFON AGENTIE", kind: "text", x: 164.309, y: 28.481, w: 19.477, h: 3.2, fontSize: 8.3, font: "bold", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NR CONTRACT", kind: "text", x: 60.456, y: 55.333, w: 35.001, h: 5.999, fontSize: 12, font: "bold", align: "center", valign: "middle", lineHeight: 1 },
  { name: "DIN", kind: "text", x: 107.549, y: 55.333, w: 50, h: 5.999, fontSize: 12, font: "bold", align: "center", valign: "middle", lineHeight: 1 },
  { name: "NUME", kind: "text", x: 40.681, y: 79.047, w: 80.002, h: 3.998, fontSize: 10, font: "bold", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "CNP_1", kind: "text", x: 22.036, y: 85.638, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_2", kind: "text", x: 28.99, y: 85.638, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_3", kind: "text", x: 35.943, y: 85.638, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_4", kind: "text", x: 42.897, y: 85.638, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_5", kind: "text", x: 49.851, y: 85.638, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_6", kind: "text", x: 56.805, y: 85.638, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_7", kind: "text", x: 63.759, y: 85.638, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_8", kind: "text", x: 70.713, y: 85.638, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_9", kind: "text", x: 77.667, y: 85.638, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_10", kind: "text", x: 84.62, y: 85.638, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_11", kind: "text", x: 91.574, y: 85.638, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_12", kind: "text", x: 98.528, y: 85.638, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "CNP_13", kind: "text", x: 105.482, y: 85.638, w: 6.557, h: 4.998, fontSize: 9, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "JUDET", kind: "text", x: 49.921, y: 92.331, w: 35.001, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "LOCALITATEA", kind: "text", x: 92.513, y: 92.331, w: 45.002, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "STRADA", kind: "text", x: 27.154, y: 97.925, w: 29.998, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NUMARUL STRAZII", kind: "text", x: 63.329, y: 97.925, w: 9.997, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "BLOC", kind: "text", x: 79.329, y: 97.925, w: 9.997, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "SCARA", kind: "text", x: 96.031, y: 97.925, w: 9.997, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "APARTAMENT", kind: "text", x: 113.089, y: 97.925, w: 9.997, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "LEGITIMAT CU", kind: "text", x: 141.793, y: 97.925, w: 9.997, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "SERIE CI", kind: "text", x: 161.32, y: 97.925, w: 9.997, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NR CI", kind: "text", x: 177.493, y: 97.925, w: 9.997, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "ELIBERAT DE", kind: "text", x: 39.511, y: 102.82, w: 54.998, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE IMPRUMUT", kind: "text", x: 79.746, y: 108.413, w: 29.998, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE IMPRUMUT1", kind: "text", x: 23.797, y: 129.523, w: 24.363, h: 3.998, fontSize: 8.5, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "NR ZILE", kind: "text", x: 51.418, y: 129.523, w: 24.363, h: 3.998, fontSize: 8.5, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "DATA SCADENTA", kind: "text", x: 79.039, y: 129.523, w: 24.363, h: 3.998, fontSize: 8.5, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "COMISION PROCENT ZI", kind: "text", x: 106.66, y: 129.523, w: 24.363, h: 3.998, fontSize: 8.5, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "COMISION", kind: "text", x: 134.281, y: 129.523, w: 24.363, h: 3.998, fontSize: 8.5, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "SUMA DE RESTITUIT", kind: "text", x: 161.903, y: 129.523, w: 24.384, h: 3.998, fontSize: 8.5, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "GARANTII", kind: "text", x: 22.036, y: 141.934, w: 166.012, h: 27.997, fontSize: 9, font: "regular", align: "left", valign: "top", lineHeight: 1.75, multiline: true },
  { name: "DISPOZITIE DE PLATA NUMARUL", kind: "text", x: 48.094, y: 173.623, w: 9.997, h: 3.998, fontSize: 8.7, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "DIN1", kind: "text", x: 65.69, y: 173.623, w: 9.997, h: 3.998, fontSize: 8.7, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NUME1", kind: "text", x: 105.631, y: 173.623, w: 45.002, h: 3.998, fontSize: 8.7, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "LEGITIMAT CU1", kind: "text", x: 22.036, y: 179.089, w: 9.997, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "SERIE CI1", kind: "text", x: 74.396, y: 179.089, w: 9.997, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NR CI1", kind: "text", x: 90.57, y: 179.089, w: 9.997, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE IMPRUMUT2", kind: "text", x: 120.866, y: 179.089, w: 9.997, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE IMPRUMUT IN SCRIS", kind: "text", x: 22.036, y: 183.984, w: 60.001, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "NR CONTRACT1", kind: "text", x: 152.993, y: 183.984, w: 9.997, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "DIN2", kind: "text", x: 168.993, y: 183.984, w: 9.997, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "CASIER_PLATA", kind: "text", x: 48.09, y: 191.843, w: 50, h: 3.998, fontSize: 8.7, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "SUMA PRIMITĂ LEI", kind: "text", x: 149.814, y: 191.074, w: 9.997, h: 3.998, fontSize: 8.7, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "CLIENT_PLATA", kind: "text", x: 138.048, y: 198.036, w: 50, h: 3.998, fontSize: 8.7, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "DISPOZITIE INCASARE", kind: "text", x: 53.386, y: 204.73, w: 9.997, h: 3.998, fontSize: 8.7, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "DISPOZITIE INCASARE DIN", kind: "text", x: 70.981, y: 204.73, w: 9.997, h: 3.998, fontSize: 8.7, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE INCASARE", kind: "text", x: 113.486, y: 204.73, w: 9.997, h: 3.998, fontSize: 8.7, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "INCASARE NR CONTRACT", kind: "text", x: 77.46, y: 210.195, w: 9.997, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "INCASARE DIN", kind: "text", x: 93.46, y: 210.195, w: 9.997, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "VALOARE INCASARE IN SCRIS", kind: "text", x: 22.036, y: 215.09, w: 90.003, h: 3.998, fontSize: 9, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "CASIER_INCASARE", kind: "text", x: 48.09, y: 222.18, w: 50, h: 3.998, fontSize: 8.7, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "CLIENT_INCASARE", kind: "text", x: 138.048, y: 222.18, w: 50, h: 3.998, fontSize: 8.7, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "DEBITOR_SIG", kind: "text", x: 89.259, y: 228.374, w: 50, h: 3.998, fontSize: 8.7, font: "regular", align: "center", valign: "bottom", lineHeight: 1 },
  { name: "DATA PRELUNGIRII", kind: "text", x: 23.797, y: 247.834, w: 17.459, h: 3.998, fontSize: 8.5, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "NR ZILE PREL", kind: "text", x: 44.514, y: 247.834, w: 17.459, h: 3.998, fontSize: 8.5, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "DATA RESTITUIRII PRELUNGIRE", kind: "text", x: 65.231, y: 247.834, w: 17.459, h: 3.998, fontSize: 8.5, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "COMISION PRELUNGIRE", kind: "text", x: 85.948, y: 247.834, w: 17.459, h: 3.998, fontSize: 8.5, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "VALOARE COMISION PREL", kind: "text", x: 106.664, y: 247.834, w: 17.459, h: 3.998, fontSize: 8.5, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "SUMA RESTITUIT PRELUNGIRE", kind: "text", x: 127.381, y: 247.834, w: 17.459, h: 3.998, fontSize: 8.5, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
  { name: "DATA RESTITUIRII PRELUNGIRE copy", kind: "text", x: 23.797, y: 255.04, w: 17.459, h: 3.998, fontSize: 8.5, font: "regular", align: "center", valign: "middle", lineHeight: 1 },
];

export const FIELDS_BY_NAME: Map<string, Field> = new Map(FIELDS.map((f) => [f.name, f]));

export function byName(name: string): Field | undefined {
  return FIELDS_BY_NAME.get(name);
}

export function cnpCells(): Field[] {
  const out: Field[] = [];
  for (let i = 1; i <= 13; i++) {
    const f = FIELDS_BY_NAME.get(`CNP_${i}`);
    if (f) out.push(f);
  }
  return out;
}
