// One-shot: walk the active contract template's schemas array and emit
// pdfLayout/contractLayout.ts (Field[]). Replace the 4 MB JSON artifact with
// an inspectable TS file the agent can read in one shot.
//
//   node scripts/extract-layout.mjs                          # default in/out
//   node scripts/extract-layout.mjs path/in.json path/out.ts
//
// Idempotent. readOnly / rectangle / (0,0)-degenerate fields become comments
// (kind: 'skip' equivalent) so they don't pollute the runtime draw loop.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const PROJECT_ROOT = path.resolve(path.dirname(__filename), "..");

const input = process.argv[2] ?? "pdfTemplates/contractTemplate2026.json";
const output = process.argv[3] ?? "pdfLayout/contractLayout.ts";

const jsonPath = path.join(PROJECT_ROOT, input);
const json = JSON.parse(fs.readFileSync(jsonPath, "utf8"));

if (!Array.isArray(json.schemas) || !Array.isArray(json.schemas[0])) {
  throw new Error(`Expected schemas[0] to be an array in ${jsonPath}`);
}

const page = json.schemas[0];
const PAGE_W_MM = page.reduce((m, s) => Math.max(m, (s.position?.x ?? 0) + (s.position?.width ?? 0)), 0);
const PAGE_H_MM = page.reduce((m, s) => Math.max(m, (s.position?.y ?? 0) + (s.position?.height ?? 0)), 0);

const out = [];
out.push(`// Generated by scripts/extract-layout.mjs from ${path.basename(input)}`);
out.push(`// ${page.length} fields; regenerated ${new Date().toISOString()}`);
out.push(`// Source bounding box (mm): ${PAGE_W_MM.toFixed(1)} wide x ${PAGE_H_MM.toFixed(1)} tall`);
out.push(`// Do not edit by hand — re-run the script after touching the source template.`);
out.push(``);
out.push(`import type { Field } from "./types";`);
out.push(``);
out.push(`export const FIELDS: Field[] = [`);

let skipped = 0;
let rendered = 0;

for (const s of page) {
  const name = s.name;
  if (!name) continue;

  const pos = s.position ?? {};
  const w = s.width ?? 0;
  const h = s.height ?? 0;
  const isDegenerate = (pos.x ?? 0) <= 0.01 && (pos.y ?? 0) <= 0.01 && w <= 1 && h <= 1;
  const skip = !!s.readOnly || s.type === "rectangle" || isDegenerate;
  const font = s.fontName?.includes("Bold") ? "bold" : "regular";
  const align = s.alignment ?? "left";
  const valign = s.verticalAlignment ?? "middle";
  const lineHeight = s.lineHeight ?? 1.2;
  const multiline = (s.lineHeight ?? 1) >= 1.5;
  const fontSize = s.fontSize ?? 10;

  const r = (n) => Math.round(n * 1000) / 1000;

  if (skip) {
    const why = s.readOnly ? "readOnly" : s.type === "rectangle" ? "rectangle" : "degenerate";
    const content = s.content ? ` content=${JSON.stringify(truncate(String(s.content), 60))}` : "";
    out.push(`  // skip: ${name} (${why})${content}`);
    skipped++;
    continue;
  }

  out.push(
    `  { name: ${JSON.stringify(name)}, kind: "text", x: ${r(pos.x)}, y: ${r(pos.y)}, w: ${r(w)}, h: ${r(h)}, fontSize: ${fontSize}, font: ${JSON.stringify(font)}, align: ${JSON.stringify(align)}, valign: ${JSON.stringify(valign)}, lineHeight: ${lineHeight}${multiline ? ", multiline: true" : ""} },`
  );
  rendered++;
}

out.push(`];`);
out.push(``);
out.push(`export const FIELDS_BY_NAME: Map<string, Field> = new Map(FIELDS.map((f) => [f.name, f]));`);
out.push(``);
out.push(`export function byName(name: string): Field | undefined {`);
out.push(`  return FIELDS_BY_NAME.get(name);`);
out.push(`}`);
out.push(``);
out.push(`export function cnpCells(): Field[] {`);
out.push(`  const out: Field[] = [];`);
out.push(`  for (let i = 1; i <= 13; i++) {`);
out.push(`    const f = FIELDS_BY_NAME.get(\`CNP_\${i}\`);`);
out.push(`    if (f) out.push(f);`);
out.push(`  }`);
out.push(`  return out;`);
out.push(`}`);

const outPath = path.join(PROJECT_ROOT, output);
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, out.join("\n") + "\n");
console.log(`Wrote ${outPath} (${rendered} rendered, ${skipped} skipped)`);

function truncate(s, n) {
  return s.length > n ? s.slice(0, n) + "…" : s;
}